# Generated by Django 2.0.8 on 2018-11-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='URL',
            new_name='book_URL',
        ),
    ]
